### ISSUE TITLE
EsNext doesn't convert var into let or const

### ISSUE THREAD

**Issue by ferrybig** [resugar/resugar#138]
Since `let` and `const` are new since ES6, EsNext should convert them. But it doesn't at the moment:

```js
var memoize = require('lodash').memoize;

var upperCase = memoize(function(string) {
  return string.toUpperCase();
});
```
Becomes
```js
import { memoize } from 'lodash';

var upperCase = memoize(function(string) {
  return string.toUpperCase();
});
```
While it should have been:
```js
import { memoize } from 'lodash';

const upperCase = memoize(function(string) {
  return string.toUpperCase();
});
```

Version: Using the [EsNext playground](https://esnext.github.io/esnext/#%0Avar%20memoize%20%3D%20require('lodash').memoize%3B%0A%0Avar%20upperCase%20%3D%20memoize(function(string)%20%7B%0A%20%20return%20string.toUpperCase()%3B%0A%7D)%3B%0A)

**Comment by eventualbuddha** [comment]
Hmm. I think it might just be that the playground is out of date. Have you verified this on your own machine? I get this after installing `esnext` globally:

```js
❯ esnext <<EOS
heredoc> var memoize = require('lodash').memoize;

var upperCase = memoize(function(string) {
  return string.toUpperCase();
});
heredoc> EOS
import { memoize } from 'lodash';

const upperCase = memoize(string => string.toUpperCase());
```

**Comment by eventualbuddha** [comment]
Closing as this is no longer relevant to the project.
