### ISSUE TITLE
async await support

### ISSUE THREAD

**Issue by Globegitter** [resugar/resugar#53]
Regenerator (see https://github.com/facebook/regenerator/issues/100 and https://github.com/facebook/regenerator/pull/101) as well as traceur both have now support for the ES7 async await syntax it would be great to have this added here as well.
While not ES6 I think it is one of the most promising new syntax additions. Any thoughts?

**Comment by keyscores** [comment]
If this is merged, can we add some examples to the docs? Thanks!
