### ISSUE TITLE
Loses inline functions in object assigned to module.exports

### ISSUE THREAD

**Issue by tivac** [resugar/resugar#92]
The `modules.commonjs` plugin doesn't seem to understand overwriting `module.exports`

``` js
module.exports = {
    controller : function() { },
    view : function() { }
};

// converts into
export { undefined as controller, undefined as view };
```

If I instead directly assign to properties on the `exports` object it does the right thing.

``` js
exports.controller = function() { };
exports.view = function() { };

// converts into
export function controller() { }
export function view() { }
```

**Comment by tivac** [comment]
Using `esnext@1.17.2` on `nodejs@5.8.0`, if it helps.

**Comment by tivac** [comment]
I'm going to try and dig into the difference between this case and [rewrites-assigning-an-object-with-simple-properties-to-module-exports-as-named-exports](https://github.com/esnext/esnext/blob/master/test/form/modules.commonjs/rewrites-assigning-an-object-with-simple-properties-to-module-exports-as-named-exports/main.js) because they look superficially similar & I assume that test is passing.

**Comment by eventualbuddha** [comment]
It's because I assume the property values are identifiers. If they're not we have to create a local binding for them and then export that binding.

**Comment by rnubel** [comment]
Related to this, an export of a single function fails with a stacktrace:

```javascript
// test.js
module.exports = {
  foo: function() { return; }
}
```

```bash
$ esnext test.js
TypeError: Cannot read property 'name' of undefined
    at rewriteSingleExportAsDefaultExport (/Users/robert/.nvm/versions/node/v6.1.0/lib/node_modules/esnext/dist/esnext.umd.js:1677:43)
    at rewriteAsExport (/Users/robert/.nvm/versions/node/v6.1.0/lib/node_modules/esnext/dist/esnext.umd.js:1630:14)
    at /Users/robert/.nvm/versions/node/v6.1.0/lib/node_modules/esnext/dist/esnext.umd.js:1609:14
    at Array.forEach (native)
```

**Comment by sheerun** [comment]
It's the same with simple numbers:

```
module.exports = {
  foo: 12,
  bar: 13
};
```

```
export { undefined as foo, undefined as bar };
```
